<?php

namespace Container8uUtBOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1whVE7eService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.1whVE7e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'orphelin' => ['privates', '.errored..service_locator.1whVE7e.App\\Entity\\DicomNonReconcilie', NULL, 'Cannot autowire service ".service_locator.1whVE7e": it needs an instance of "App\\Entity\\DicomNonReconcilie" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'orphelin' => 'App\\Entity\\DicomNonReconcilie',
        ]);

        if (isset($container->privates['.service_locator.1whVE7e'])) {
            return $container->privates['.service_locator.1whVE7e'];
        }

        return $container->privates['.service_locator.1whVE7e'] = $instance;
    }
}
