<?php

namespace Container8uUtBOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDicomWebhookControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DicomWebhookController' shared autowired service.
     *
     * @return \App\Controller\DicomWebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DicomWebhookController'] = $instance = new \App\Controller\DicomWebhookController(($container->privates['App\\Service\\OrthancService'] ?? $container->load('getOrthancServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\DicomWebhookController', $container));

        return $instance;
    }
}
