<?php

namespace Container8uUtBOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDicomReconciliationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DicomReconciliationController' shared autowired service.
     *
     * @return \App\Controller\DicomReconciliationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DicomReconciliationController'] = $instance = new \App\Controller\DicomReconciliationController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\DicomReconciliationController', $container));

        return $instance;
    }
}
