<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__AuditLog__CLASSMETADATA__' => 0,
'App__Entity__DicomNonReconcilie__CLASSMETADATA__' => 1,
'App__Entity__Examen__CLASSMETADATA__' => 2,
'App__Entity__Machine__CLASSMETADATA__' => 3,
'App__Entity__Patient__CLASSMETADATA__' => 4,
'App__Entity__ResultatDicom__CLASSMETADATA__' => 5,
'App__Entity__Utilisateur__CLASSMETADATA__' => 6,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\AuditLog',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'action' => $o[2],
                    'dateHeure' => $o[3],
                    'adresseIP' => $o[4],
                    'details' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'action' => 'action',
                    'date_heure' => 'dateHeure',
                    'adresse_ip' => 'adresseIP',
                    'details' => 'details',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'action' => 'action',
                    'dateHeure' => 'date_heure',
                    'adresseIP' => 'adresse_ip',
                    'details' => 'details',
                ],
            ],
            'table' => [
                [
                    'name' => 'audit_log',
                ],
            ],
            'associationMappings' => [
                [
                    'utilisateur' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\AuditLog',
                7 => 'utilisateur_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'datetime',
                'string',
                'text',
            ],
            'fieldName' => [
                1 => 'id',
                'action',
                'dateHeure',
                'adresseIP',
                'details',
            ],
            'columnName' => [
                1 => 'id',
                'action',
                'date_heure',
                'adresse_ip',
                'details',
            ],
            'length' => [
                2 => 100,
                4 => 45,
            ],
            'nullable' => [
                4 => true,
                true,
                7 => true,
            ],
            'fetch' => [
                6 => 2,
            ],
            'sourceEntity' => [
                6 => 'App\\Entity\\AuditLog',
            ],
            'sourceToTargetKeyColumns' => [
                6 => [
                    'utilisateur_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                6 => [
                    'id' => 'utilisateur_id',
                ],
            ],
            'joinColumns' => [
                6 => [
                    $o[7],
                ],
            ],
            'joinColumnFieldNames' => [
                6 => [
                    'utilisateur_id' => 'utilisateur_id',
                ],
            ],
            'referencedColumnName' => [
                7 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                6 => 'utilisateur',
            ],
            'targetEntity' => [
                6 => 'App\\Entity\\Utilisateur',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\DicomNonReconcilie',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\DicomNonReconcilieRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'orthancInstanceId' => $o[2],
                    'patientIdDicom' => $o[3],
                    'patientNomDicom' => $o[4],
                    'studyInstanceUid' => $o[5],
                    'modality' => $o[6],
                    'metadonneesBrutes' => $o[7],
                    'receivedAt' => $o[8],
                    'statut' => $o[9],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'orthanc_instance_id' => 'orthancInstanceId',
                    'patient_id_dicom' => 'patientIdDicom',
                    'patient_nom_dicom' => 'patientNomDicom',
                    'study_instance_uid' => 'studyInstanceUid',
                    'modality' => 'modality',
                    'metadonnees_brutes' => 'metadonneesBrutes',
                    'received_at' => 'receivedAt',
                    'statut' => 'statut',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'orthancInstanceId' => 'orthanc_instance_id',
                    'patientIdDicom' => 'patient_id_dicom',
                    'patientNomDicom' => 'patient_nom_dicom',
                    'studyInstanceUid' => 'study_instance_uid',
                    'modality' => 'modality',
                    'metadonneesBrutes' => 'metadonnees_brutes',
                    'receivedAt' => 'received_at',
                    'statut' => 'statut',
                ],
            ],
            'table' => [
                [
                    'name' => 'dicom_non_reconcilie',
                ],
            ],
            'associationMappings' => [
                [
                    'examenReconcilie' => $o[10],
                ],
            ],
            'idGenerator' => [
                $o[12],
            ],
            'name' => [
                'App\\Entity\\DicomNonReconcilie',
                11 => 'examen_reconcilie_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'string',
                'json',
                'datetime_immutable',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'orthancInstanceId',
                'patientIdDicom',
                'patientNomDicom',
                'studyInstanceUid',
                'modality',
                'metadonneesBrutes',
                'receivedAt',
                'statut',
            ],
            'columnName' => [
                1 => 'id',
                'orthanc_instance_id',
                'patient_id_dicom',
                'patient_nom_dicom',
                'study_instance_uid',
                'modality',
                'metadonnees_brutes',
                'received_at',
                'statut',
            ],
            'length' => [
                2 => 255,
                255,
                255,
                255,
                255,
                9 => 50,
            ],
            'nullable' => [
                3 => true,
                true,
                true,
                true,
                true,
                11 => true,
            ],
            'fetch' => [
                10 => 2,
            ],
            'sourceEntity' => [
                10 => 'App\\Entity\\DicomNonReconcilie',
            ],
            'sourceToTargetKeyColumns' => [
                10 => [
                    'examen_reconcilie_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                10 => [
                    'id' => 'examen_reconcilie_id',
                ],
            ],
            'joinColumns' => [
                10 => [
                    $o[11],
                ],
            ],
            'joinColumnFieldNames' => [
                10 => [
                    'examen_reconcilie_id' => 'examen_reconcilie_id',
                ],
            ],
            'deferrable' => [
                11 => false,
            ],
            'unique' => [
                11 => false,
            ],
            'referencedColumnName' => [
                11 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                10 => 'examenReconcilie',
            ],
            'targetEntity' => [
                10 => 'App\\Entity\\Examen',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneInverseSideMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Examen',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ExamenRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'date' => $o[2],
                    'type' => $o[3],
                    'statut' => $o[4],
                    'dateModifStatut' => $o[5],
                    'description' => $o[6],
                    'compteRendu' => $o[7],
                    'datePrevue' => $o[8],
                    'studyInstanceUid' => $o[9],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                    'type' => 'type',
                    'statut' => 'statut',
                    'date_modif_statut' => 'dateModifStatut',
                    'description' => 'description',
                    'compte_rendu' => 'compteRendu',
                    'date_prevue' => 'datePrevue',
                    'study_instance_uid' => 'studyInstanceUid',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                    'type' => 'type',
                    'statut' => 'statut',
                    'dateModifStatut' => 'date_modif_statut',
                    'description' => 'description',
                    'compteRendu' => 'compte_rendu',
                    'datePrevue' => 'date_prevue',
                    'studyInstanceUid' => 'study_instance_uid',
                ],
            ],
            'table' => [
                [
                    'name' => 'examen',
                ],
            ],
            'associationMappings' => [
                [
                    'patient' => $o[10],
                    'machine' => $o[12],
                    'medecin' => $o[14],
                    'resultatDicom' => $o[16],
                ],
            ],
            'idGenerator' => [
                $o[17],
            ],
            'name' => [
                'App\\Entity\\Examen',
                11 => 'patient_id',
                13 => 'machine_id',
                15 => 'medecin_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime',
                'string',
                'string',
                'datetime',
                'string',
                'text',
                'datetime',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'date',
                'type',
                'statut',
                'dateModifStatut',
                'description',
                'compteRendu',
                'datePrevue',
                'studyInstanceUid',
            ],
            'columnName' => [
                1 => 'id',
                'date',
                'type',
                'statut',
                'date_modif_statut',
                'description',
                'compte_rendu',
                'date_prevue',
                'study_instance_uid',
            ],
            'length' => [
                3 => 10,
                6 => 500,
                9 => 255,
            ],
            'enumType' => [
                4 => 'App\\Enum\\StatutExamen',
            ],
            'nullable' => [
                5 => true,
                true,
                true,
                true,
                true,
                11 => false,
                13 => false,
                15 => true,
            ],
            'fetch' => [
                10 => 2,
                12 => 2,
                14 => 2,
                16 => 2,
            ],
            'sourceEntity' => [
                10 => 'App\\Entity\\Examen',
                12 => 'App\\Entity\\Examen',
                14 => 'App\\Entity\\Examen',
                16 => 'App\\Entity\\Examen',
            ],
            'inversedBy' => [
                10 => 'examens',
            ],
            'sourceToTargetKeyColumns' => [
                10 => [
                    'patient_id' => 'id',
                ],
                12 => [
                    'machine_id' => 'id',
                ],
                14 => [
                    'medecin_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                10 => [
                    'id' => 'patient_id',
                ],
                12 => [
                    'id' => 'machine_id',
                ],
                14 => [
                    'id' => 'medecin_id',
                ],
            ],
            'joinColumns' => [
                10 => [
                    $o[11],
                ],
                12 => [
                    $o[13],
                ],
                14 => [
                    $o[15],
                ],
            ],
            'joinColumnFieldNames' => [
                10 => [
                    'patient_id' => 'patient_id',
                ],
                12 => [
                    'machine_id' => 'machine_id',
                ],
                14 => [
                    'medecin_id' => 'medecin_id',
                ],
            ],
            'deferrable' => [
                11 => false,
                13 => false,
                15 => false,
            ],
            'unique' => [
                11 => false,
                13 => false,
                15 => false,
            ],
            'referencedColumnName' => [
                11 => 'id',
                13 => 'id',
                15 => 'id',
            ],
            'cascade' => [
                16 => [
                    'persist',
                ],
            ],
            'mappedBy' => [
                16 => 'examen',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                10 => 'patient',
                12 => 'machine',
                14 => 'medecin',
                16 => 'resultatDicom',
            ],
            'targetEntity' => [
                10 => 'App\\Entity\\Patient',
                12 => 'App\\Entity\\Machine',
                14 => 'App\\Entity\\Utilisateur',
                16 => 'App\\Entity\\ResultatDicom',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Machine',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'modalite' => $o[3],
                    'aeTitle' => $o[4],
                    'adresseIP' => $o[5],
                    'statut' => $o[6],
                    'dateDebut' => $o[7],
                    'dateFin' => $o[8],
                    'description' => $o[9],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'modalite' => 'modalite',
                    'ae_title' => 'aeTitle',
                    'adresse_ip' => 'adresseIP',
                    'statut' => 'statut',
                    'date_debut' => 'dateDebut',
                    'date_fin' => 'dateFin',
                    'description' => 'description',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'modalite' => 'modalite',
                    'aeTitle' => 'ae_title',
                    'adresseIP' => 'adresse_ip',
                    'statut' => 'statut',
                    'dateDebut' => 'date_debut',
                    'dateFin' => 'date_fin',
                    'description' => 'description',
                ],
            ],
            'table' => [
                [
                    'name' => 'machine',
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\Machine',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'string',
                'datetime',
                'datetime',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'modalite',
                'aeTitle',
                'adresseIP',
                'statut',
                'dateDebut',
                'dateFin',
                'description',
            ],
            'columnName' => [
                1 => 'id',
                'nom',
                'modalite',
                'ae_title',
                'adresse_ip',
                'statut',
                'date_debut',
                'date_fin',
                'description',
            ],
            'length' => [
                2 => 100,
                10,
                64,
                45,
                9 => 255,
            ],
            'enumType' => [
                6 => 'App\\Enum\\StatutMachine',
            ],
            'nullable' => [
                7 => true,
                true,
                true,
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Patient',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'patientId' => $o[2],
                    'nom' => $o[3],
                    'prenom' => $o[4],
                    'cin' => $o[5],
                    'dateNaissance' => $o[6],
                    'sexe' => $o[7],
                    'telephone' => $o[8],
                    'adresse' => $o[9],
                    'actif' => $o[10],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'patient_id' => 'patientId',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'cin' => 'cin',
                    'date_naissance' => 'dateNaissance',
                    'sexe' => 'sexe',
                    'telephone' => 'telephone',
                    'adresse' => 'adresse',
                    'actif' => 'actif',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'patientId' => 'patient_id',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'cin' => 'cin',
                    'dateNaissance' => 'date_naissance',
                    'sexe' => 'sexe',
                    'telephone' => 'telephone',
                    'adresse' => 'adresse',
                    'actif' => 'actif',
                ],
            ],
            'table' => [
                [
                    'name' => 'patient',
                ],
            ],
            'associationMappings' => [
                [
                    'examens' => $o[11],
                ],
            ],
            'idGenerator' => [
                $o[12],
            ],
            'name' => [
                'App\\Entity\\Patient',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'date',
                'string',
                'string',
                'string',
                'boolean',
            ],
            'fieldName' => [
                1 => 'id',
                'patientId',
                'nom',
                'prenom',
                'cin',
                'dateNaissance',
                'sexe',
                'telephone',
                'adresse',
                'actif',
            ],
            'columnName' => [
                1 => 'id',
                'patient_id',
                'nom',
                'prenom',
                'cin',
                'date_naissance',
                'sexe',
                'telephone',
                'adresse',
                'actif',
            ],
            'length' => [
                2 => 20,
                100,
                100,
                20,
                7 => 10,
                20,
                255,
            ],
            'unique' => [
                2 => true,
                5 => true,
            ],
            'nullable' => [
                8 => true,
                true,
            ],
            'fetch' => [
                11 => 2,
            ],
            'sourceEntity' => [
                11 => 'App\\Entity\\Patient',
            ],
            'mappedBy' => [
                11 => 'patient',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                11 => 'examens',
            ],
            'targetEntity' => [
                11 => 'App\\Entity\\Examen',
            ],
        ],
    ],
    $o[0],
    []
); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\ResultatDicom',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ResultatDicomRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'orthancInstanceId' => $o[2],
                    'studyInstanceUid' => $o[3],
                    'seriesInstanceUid' => $o[4],
                    'modality' => $o[5],
                    'receivedAt' => $o[6],
                    'orthancUrl' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'orthanc_instance_id' => 'orthancInstanceId',
                    'study_instance_uid' => 'studyInstanceUid',
                    'series_instance_uid' => 'seriesInstanceUid',
                    'modality' => 'modality',
                    'received_at' => 'receivedAt',
                    'orthanc_url' => 'orthancUrl',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'orthancInstanceId' => 'orthanc_instance_id',
                    'studyInstanceUid' => 'study_instance_uid',
                    'seriesInstanceUid' => 'series_instance_uid',
                    'modality' => 'modality',
                    'receivedAt' => 'received_at',
                    'orthancUrl' => 'orthanc_url',
                ],
            ],
            'table' => [
                [
                    'name' => 'resultat_dicom',
                ],
            ],
            'associationMappings' => [
                [
                    'examen' => $o[8],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\ResultatDicom',
                9 => 'examen_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'datetime_immutable',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'orthancInstanceId',
                'studyInstanceUid',
                'seriesInstanceUid',
                'modality',
                'receivedAt',
                'orthancUrl',
            ],
            'columnName' => [
                1 => 'id',
                'orthanc_instance_id',
                'study_instance_uid',
                'series_instance_uid',
                'modality',
                'received_at',
                'orthanc_url',
            ],
            'length' => [
                2 => 255,
                255,
                255,
                255,
                7 => 255,
            ],
            'nullable' => [
                4 => true,
                true,
                7 => true,
                9 => false,
            ],
            'fetch' => [
                8 => 2,
            ],
            'sourceEntity' => [
                8 => 'App\\Entity\\ResultatDicom',
            ],
            'sourceToTargetKeyColumns' => [
                8 => [
                    'examen_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                8 => [
                    'id' => 'examen_id',
                ],
            ],
            'joinColumns' => [
                8 => [
                    $o[9],
                ],
            ],
            'joinColumnFieldNames' => [
                8 => [
                    'examen_id' => 'examen_id',
                ],
            ],
            'deferrable' => [
                9 => false,
            ],
            'unique' => [
                9 => false,
            ],
            'referencedColumnName' => [
                9 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                8 => 'examen',
            ],
            'targetEntity' => [
                8 => 'App\\Entity\\Examen',
            ],
        ],
    ],
    $o[0],
    []
); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Utilisateur',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'login' => $o[2],
                    'motDePasse' => $o[3],
                    'role' => $o[4],
                    'nom' => $o[5],
                    'prenom' => $o[6],
                    'email' => $o[7],
                    'actif' => $o[8],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'login' => 'login',
                    'mot_de_passe' => 'motDePasse',
                    'role' => 'role',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'actif' => 'actif',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'login' => 'login',
                    'motDePasse' => 'mot_de_passe',
                    'role' => 'role',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'actif' => 'actif',
                ],
            ],
            'table' => [
                [
                    'name' => 'utilisateur',
                ],
            ],
            'idGenerator' => [
                $o[9],
            ],
            'name' => [
                'App\\Entity\\Utilisateur',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'boolean',
            ],
            'fieldName' => [
                1 => 'id',
                'login',
                'motDePasse',
                'role',
                'nom',
                'prenom',
                'email',
                'actif',
            ],
            'columnName' => [
                1 => 'id',
                'login',
                'mot_de_passe',
                'role',
                'nom',
                'prenom',
                'email',
                'actif',
            ],
            'length' => [
                2 => 100,
                255,
                5 => 100,
                100,
                180,
            ],
            'unique' => [
                2 => true,
            ],
            'enumType' => [
                4 => 'App\\Enum\\Role',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
