<?php

namespace ContainerKnR37Ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8yLhS74Service extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.8yLhS74' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8yLhS74'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'examenRepository' => ['privates', 'App\\Repository\\ExamenRepository', 'getExamenRepositoryService', true],
            'machineRepository' => ['privates', 'App\\Repository\\MachineRepository', 'getMachineRepositoryService', true],
            'patientRepository' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService', true],
        ], [
            'examenRepository' => 'App\\Repository\\ExamenRepository',
            'machineRepository' => 'App\\Repository\\MachineRepository',
            'patientRepository' => 'App\\Repository\\PatientRepository',
        ]);
    }
}
