<?php

namespace ContainerKnR37Ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AIkDQkQService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.AIkDQkQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dicomNonReconcilieRepository' => ['privates', 'App\\Repository\\DicomNonReconcilieRepository', 'getDicomNonReconcilieRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dicomNonReconcilieRepository' => 'App\\Repository\\DicomNonReconcilieRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.AIkDQkQ'])) {
            return $container->privates['.service_locator.AIkDQkQ'];
        }

        return $container->privates['.service_locator.AIkDQkQ'] = $instance;
    }
}
