<?php

namespace ContainerKnR37Ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UwNbc9Service extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.uw_nbc9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uw_nbc9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dicomNonReconcilieRepository' => ['privates', 'App\\Repository\\DicomNonReconcilieRepository', 'getDicomNonReconcilieRepositoryService', true],
        ], [
            'dicomNonReconcilieRepository' => 'App\\Repository\\DicomNonReconcilieRepository',
        ]);
    }
}
