<?php

namespace ContainerKnR37Ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ExamenController::list' => ['privates', '.service_locator.uw_nbc9', 'get_ServiceLocator_UwNbc9Service', true],
            'App\\Controller\\ExamenController::update' => ['privates', '.service_locator.AIkDQkQ', 'get_ServiceLocator_AIkDQkQService', true],
            'App\\Controller\\ExamenPageController::index' => ['privates', '.service_locator.8yLhS74', 'get_ServiceLocator_8yLhS74Service', true],
            'App\\Controller\\MachineController::getAll' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MachineController::getMachine' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MachineController::updateStatut' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.fxlRNcI', 'get_ServiceLocator_FxlRNcIService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ExamenController:list' => ['privates', '.service_locator.uw_nbc9', 'get_ServiceLocator_UwNbc9Service', true],
            'App\\Controller\\ExamenController:update' => ['privates', '.service_locator.AIkDQkQ', 'get_ServiceLocator_AIkDQkQService', true],
            'App\\Controller\\ExamenPageController:index' => ['privates', '.service_locator.8yLhS74', 'get_ServiceLocator_8yLhS74Service', true],
            'App\\Controller\\MachineController:getAll' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MachineController:getMachine' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MachineController:updateStatut' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.fxlRNcI', 'get_ServiceLocator_FxlRNcIService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ExamenController::list' => '?',
            'App\\Controller\\ExamenController::update' => '?',
            'App\\Controller\\ExamenPageController::index' => '?',
            'App\\Controller\\MachineController::getAll' => '?',
            'App\\Controller\\MachineController::getMachine' => '?',
            'App\\Controller\\MachineController::updateStatut' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ExamenController:list' => '?',
            'App\\Controller\\ExamenController:update' => '?',
            'App\\Controller\\ExamenPageController:index' => '?',
            'App\\Controller\\MachineController:getAll' => '?',
            'App\\Controller\\MachineController:getMachine' => '?',
            'App\\Controller\\MachineController:updateStatut' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));

        if (isset($container->privates['argument_resolver.service'])) {
            return $container->privates['argument_resolver.service'];
        }

        return $container->privates['argument_resolver.service'] = $instance;
    }
}
