<?php

namespace ContainerKnR37Ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrthancServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Service\OrthancService' shared autowired service.
     *
     * @return \App\Service\OrthancService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\OrthancService'] = new \App\Service\OrthancService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ExamenRepository'] ?? $container->load('getExamenRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
