<?php

namespace ContainerYpIrYQ7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDicomNonReconcilieRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DicomNonReconcilieRepository' shared autowired service.
     *
     * @return \App\Repository\DicomNonReconcilieRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DicomNonReconcilieRepository'] = new \App\Repository\DicomNonReconcilieRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
