<?php

namespace ContainerYpIrYQ7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDicomNonReconcilieService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.1whVE7e.App\Entity\DicomNonReconcilie' shared service.
     *
     * @return \App\Entity\DicomNonReconcilie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1whVE7e": it needs an instance of "App\\Entity\\DicomNonReconcilie" but this type has been excluded in "config/services.yaml".');
    }
}
