<?php

namespace ContainerYpIrYQ7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamenServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ExamenService' shared autowired service.
     *
     * @return \App\Service\ExamenService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ExamenService'] = new \App\Service\ExamenService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ExamenRepository'] ?? $container->load('getExamenRepositoryService')));
    }
}
