<?php

namespace ContainerYpIrYQ7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResultatDicomRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ResultatDicomRepository' shared autowired service.
     *
     * @return \App\Repository\ResultatDicomRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ResultatDicomRepository'] = new \App\Repository\ResultatDicomRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
