<?php

namespace Container7fuxxmz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDicomMppsControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\DicomMppsController' shared autowired service.
     *
     * @return \App\Controller\DicomMppsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DicomMppsController'] = $instance = new \App\Controller\DicomMppsController(($container->privates['App\\Repository\\ExamenRepository'] ?? $container->load('getExamenRepositoryService')), ($container->privates['App\\Service\\ExamenService'] ?? $container->load('getExamenServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\DicomMppsController', $container));

        return $instance;
    }
}
