<?php

namespace Container7fuxxmz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDicomWorklistControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\DicomWorklistController' shared autowired service.
     *
     * @return \App\Controller\DicomWorklistController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DicomWorklistController'] = $instance = new \App\Controller\DicomWorklistController(($container->privates['App\\Repository\\ExamenRepository'] ?? $container->load('getExamenRepositoryService')), ($container->privates['App\\Service\\ExamenService'] ?? $container->load('getExamenServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\DicomWorklistController', $container));

        return $instance;
    }
}
