<?php

namespace Container7fuxxmz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamenControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\ExamenController' shared autowired service.
     *
     * @return \App\Controller\ExamenController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ExamenController'] = $instance = new \App\Controller\ExamenController(($container->privates['App\\Service\\ExamenService'] ?? $container->load('getExamenServiceService')), ($container->privates['App\\Repository\\ExamenRepository'] ?? $container->load('getExamenRepositoryService')), ($container->privates['App\\Repository\\ResultatDicomRepository'] ?? $container->load('getResultatDicomRepositoryService')), ($container->privates['App\\Service\\OrthancService'] ?? $container->load('getOrthancServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->services['router'] ?? self::getRouterService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ExamenController', $container));

        return $instance;
    }
}
