<?php

namespace Container7fuxxmz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMachineControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\MachineController' shared autowired service.
     *
     * @return \App\Controller\MachineController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MachineController'] = $instance = new \App\Controller\MachineController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\MachineController', $container));

        return $instance;
    }
}
