<?php

namespace Container7fuxxmz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPatientControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\PatientController' shared autowired service.
     *
     * @return \App\Controller\PatientController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Repository\\PatientRepository'] ?? $container->load('getPatientRepositoryService'));

        $container->services['App\\Controller\\PatientController'] = $instance = new \App\Controller\PatientController(new \App\Service\PatientService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), $a), $a);

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PatientController', $container));

        return $instance;
    }
}
