<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7fuxxmz\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7fuxxmz/App_KernelDevContainer.php') {
    touch(__DIR__.'/Container7fuxxmz.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\Container7fuxxmz\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \Container7fuxxmz\App_KernelDevContainer([
    'container.build_hash' => '7fuxxmz',
    'container.build_id' => '77b9b02d',
    'container.build_time' => 1777385641,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7fuxxmz');
