<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8uUtBOr\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8uUtBOr/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container8uUtBOr.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container8uUtBOr\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container8uUtBOr\App_KernelProdContainer([
    'container.build_hash' => '8uUtBOr',
    'container.build_id' => '98fee468',
    'container.build_time' => 1776937297,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8uUtBOr');
